lst = ["ACTOR_IN_A_LEADING_ROLE",
"ACTOR_IN_A_SUPPORTING_ROLE",
"ACTRESS_IN_A_LEADING_ROLE",
"ACTRESS_IN_A_SUPPORTING_ROLE",
"ANIMATED_FEATURE_FILM",
"CINEMATOGRAPHY",
"COSTUME_DESIGN",
"DIRECTING",
"FILM_EDITING",
"FOREIGN_LANGUAGE_FILM",
"MAKEUP_AND_HAIRSTYLING",
"MUSIC_ORIGINAL_SCORE",
"BEST_PICTURE",
"PRODUCTION_DESIGN",
"SOUND_EDITING",
"SOUND_MIXING",
"VISUAL_EFFECTS",
"WRITING_ADAPTED_SCREENPLAY",
"WRITING_ORIGINAL_SCREENPLAY"]

winner = [
"JOAQUIN_PHOENIX",
"BRAD_PITT",
"RENÉE_ZELLWEGER",
"LAURA_DERN",
"TOY_STORY_4",
"1917",
"LITTLE_WOMEN",
"PARASITE",
"FORD_V_FERRARI",
"PARASITE",
"BOMBSHELL",
"JOKER",
"PARASITE",
"ONCE_UPON_A_TIME_IN_HOLLYWOOD",
"FORD_V_FERRARI",
"1917",
"1917",
"JOJO_RABBIT",
"PARASITE"]

print(len(lst), len(winner))

for i in range(len(lst)):
    print(f"WinnerOscar({winner[i].lower()}, {lst[i].lower()}).")
