lst = ["ACTOR_IN_A_LEADING_ROLE",
"ACTOR_IN_A_SUPPORTING_ROLE",
"ACTRESS_IN_A_LEADING_ROLE",
"ACTRESS_IN_A_SUPPORTING_ROLE",
"ANIMATED_FEATURE_FILM",
"CINEMATOGRAPHY",
"COSTUME_DESIGN",
"DIRECTING",
"FILM_EDITING",
"FOREIGN_LANGUAGE_FILM",
"MAKEUP_AND_HAIRSTYLING",
"MUSIC_ORIGINAL_SCORE",
"BEST_PICTURE",
"PRODUCTION_DESIGN",
"SOUND_EDITING",
"SOUND_MIXING",
"VISUAL_EFFECTS",
"WRITING_ADAPTED_SCREENPLAY",
"WRITING_ORIGINAL_SCREENPLAY"]

winner = [
"RAMI_MALEK",
"MAHERSHALA_ALI",
"OLIVIA_COLMAN",
"REGINA_KING",
"SPIDER_MAN_INTO_THE_SPIDER-VERSE",
"ROMA",
"BLACK_PANTHER",
"ROMA",
"BOHEMIAN_RHAPSODY",
"ROMA",
"VICE",
"BLACK_PANTHER",
"GREEN_BOOK",
"BLACK_PANTHER",
"BOHEMIAN_RHAPSODY",
"BOHEMIAN_RHAPSODY",
"FIRST_MAN",
"BLACKKKLANSMAN",
"GREEN_BOOK"]

print(len(lst), len(winner))

for i in range(len(lst)):
    print(f"oscarAward({lst[i].lower()}).")
